_wandb:
    value:
        cli_version: 0.21.1
        e:
            hdmk00b7go6emn38ysw4nt9ygdsrjbtu:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 8
                    ramTotalBytes: "25769803776"
                codePath: Test.py
                codePathLocal: Test.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "237668409344"
                email: salvatore.nocita25@gmail.com
                executable: /Users/lilshoe/miniconda3/bin/python
                git:
                    commit: dc48132e9d24109399e8eb739f8fceda42e9b1dc
                    remote: https://github.com/LucianoScarpino/Newton_Methods_Optimization.git
                host: MacBook-Pro.local
                memory:
                    total: "25769803776"
                os: macOS-15.6-arm64-arm-64bit-Mach-O
                program: /Users/lilshoe/Library/Mobile Documents/com~apple~CloudDocs/Politecnico Torino/Anno 2024-2025/Primo Semestre/Numerical Optimization/Projects_Code/Numerical/Test.py
                python: CPython 3.13.2
                root: /Users/lilshoe/Library/Mobile Documents/com~apple~CloudDocs/Politecnico Torino/Anno 2024-2025/Primo Semestre/Numerical Optimization/Projects_Code/Numerical
                startedAt: "2025-08-17T17:48:09.310254Z"
                writerId: hdmk00b7go6emn38ysw4nt9ygdsrjbtu
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 53
            "2":
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.2
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
function:
    value: extended_rosenbrock
method:
    value: modified
"n":
    value: 1000
