_wandb:
    value:
        cli_version: 0.21.1
        e:
            k23ucmma0lkzk3a244ylxazkimnoyqnf:
                codePath: Test.py
                codePathLocal: Test.py
                email: salvatore.nocita25@gmail.com
                executable: C:\Users\salvo\AppData\Local\Programs\Python\Python312\python.exe
                git:
                    commit: a949b4e85a0d985a56479f507fb42b0bbab1fdc8
                    remote: https://github.com/LucianoScarpino/Newton_Methods_Optimization.git
                host: LAPTOP-ALB2CGFI
                os: Windows-11-10.0.26100-SP0
                program: c:\Users\salvo\OneDrive\Desktop\model\Newton_Methods_Optimization\Test.py
                python: CPython 3.12.7
                root: C:\Users\salvo\OneDrive\Desktop\model\Newton_Methods_Optimization
                startedAt: "2025-08-17T15:05:15.417223Z"
                writerId: k23ucmma0lkzk3a244ylxazkimnoyqnf
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 53
            "2":
                - 53
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.12.7
            "5": 0.21.1
            "8":
                - 3
            "12": 0.21.1
            "13": windows-amd64
function:
    value: extended_rosenbrock
method:
    value: modified
"n":
    value: 50
