_wandb:
    value:
        cli_version: 0.21.1
        e:
            qs20zmm6sp3o722wqfyt7z011hhdv8u4:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 8
                    ramTotalBytes: "25769803776"
                codePath: Test.py
                codePathLocal: Test.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "249839083520"
                email: salvatore.nocita25@gmail.com
                executable: /Users/lilshoe/miniconda3/bin/python
                git:
                    commit: df9531ea9650a1c151ae2bc61bbcfa09a6a74362
                    remote: https://github.com/LucianoScarpino/Newton_Methods_Optimization.git
                host: Mac.lan
                memory:
                    total: "25769803776"
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: /Users/lilshoe/Library/Mobile Documents/com~apple~CloudDocs/Politecnico Torino/Anno 2024-2025/Primo Semestre/Numerical Optimization/Projects_Code/Numerical/Test.py
                python: CPython 3.13.2
                root: /Users/lilshoe/Library/Mobile Documents/com~apple~CloudDocs/Politecnico Torino/Anno 2024-2025/Primo Semestre/Numerical Optimization/Projects_Code/Numerical
                startedAt: "2025-08-24T14:30:25.168290Z"
                writerId: qs20zmm6sp3o722wqfyt7z011hhdv8u4
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 53
            "2":
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.2
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
function:
    value: broyden_tridiagonal_function
method:
    value: truncated
"n":
    value: 10000
