_wandb:
    value:
        cli_version: 0.21.1
        e:
            3tsbfqw2347xfp0aknk7jfoxd9f8w46k:
                codePath: Test.py
                codePathLocal: Test.py
                email: salvatore.nocita25@gmail.com
                executable: /Users/lilshoe/miniconda3/bin/python
                git:
                    commit: 318b9cdc83455aae92c0fbea230d84533a589ab9
                    remote: https://github.com/LucianoScarpino/Newton_Methods_Optimization.git
                host: MacBook-Pro.local
                os: macOS-15.6-arm64-arm-64bit-Mach-O
                program: /Users/lilshoe/Library/Mobile Documents/com~apple~CloudDocs/Politecnico Torino/Anno 2024-2025/Primo Semestre/Numerical Optimization/Projects_Code/Numerical/Test.py
                python: CPython 3.13.2
                root: /Users/lilshoe/Library/Mobile Documents/com~apple~CloudDocs/Politecnico Torino/Anno 2024-2025/Primo Semestre/Numerical Optimization/Projects_Code/Numerical
                startedAt: "2025-08-19T17:19:01.061888Z"
                writerId: 3tsbfqw2347xfp0aknk7jfoxd9f8w46k
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 53
            "2":
                - 53
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.13.2
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
function:
    value: extended_powell
method:
    value: truncated
"n":
    value: 1000
