_wandb:
    value:
        cli_version: 0.21.1
        e:
            yxvfq6lxvd0qx605yvmiqi4gonemw501:
                codePath: Test.py
                codePathLocal: Test.py
                email: salvatore.nocita25@gmail.com
                executable: /Users/lilshoe/miniconda3/bin/python
                git:
                    commit: 8bd3d1e8d6ab91fa069f3454cb749ab03049570f
                    remote: https://github.com/LucianoScarpino/Newton_Methods_Optimization.git
                host: Mac.lan
                os: macOS-15.6-arm64-arm-64bit-Mach-O
                program: /Users/lilshoe/Library/Mobile Documents/com~apple~CloudDocs/Politecnico Torino/Anno 2024-2025/Primo Semestre/Numerical Optimization/Projects_Code/Numerical/Test.py
                python: CPython 3.13.2
                root: /Users/lilshoe/Library/Mobile Documents/com~apple~CloudDocs/Politecnico Torino/Anno 2024-2025/Primo Semestre/Numerical Optimization/Projects_Code/Numerical
                startedAt: "2025-08-18T20:11:31.843434Z"
                writerId: yxvfq6lxvd0qx605yvmiqi4gonemw501
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 53
            "2":
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.2
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
function:
    value: extended_powell
method:
    value: modified
"n":
    value: 1000
