_wandb:
    value:
        cli_version: 0.21.3
        e:
            ov83ct043dw1qi99tl33tg5u8twng9hl:
                codePath: Test.py
                codePathLocal: Test.py
                email: salvatore.nocita25@gmail.com
                executable: /usr/local/bin/python3.10
                git:
                    commit: c463af8443edb3a77d943a639c7ae5175a11f32f
                    remote: https://github.com/LucianoScarpino/Newton_Methods_Optimization.git
                host: Mac.lan
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/lilshoe/Library/Mobile Documents/com~apple~CloudDocs/Politecnico Torino/Anno 2024-2025/Primo Semestre/Numerical Optimization/Projects_Code/Numerical/Test.py
                python: CPython 3.10.0
                root: /Users/lilshoe/Library/Mobile Documents/com~apple~CloudDocs/Politecnico Torino/Anno 2024-2025/Primo Semestre/Numerical Optimization/Projects_Code/Numerical
                startedAt: "2025-09-01T16:52:49.527214Z"
                writerId: ov83ct043dw1qi99tl33tg5u8twng9hl
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 53
            "2":
                - 53
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.10.0
            "5": 0.21.3
            "12": 0.21.3
            "13": darwin-arm64
function:
    value: extended_powell
method:
    value: modified
"n":
    value: 1000
