_wandb:
    value:
        cli_version: 0.21.1
        e:
            y6o1chsyvwf63dgdsgt5jzljv5rz5eqf:
                codePath: Test.py
                codePathLocal: Test.py
                email: salvatore.nocita25@gmail.com
                executable: /Users/lilshoe/miniconda3/bin/python
                git:
                    commit: 66500fe3cc6bd3a190e532e7498b34e9d789bffe
                    remote: https://github.com/LucianoScarpino/Newton_Methods_Optimization.git
                host: Mac.lan
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: /Users/lilshoe/Library/Mobile Documents/com~apple~CloudDocs/Politecnico Torino/Anno 2024-2025/Primo Semestre/Numerical Optimization/Projects_Code/Numerical/Test.py
                python: CPython 3.13.2
                root: /Users/lilshoe/Library/Mobile Documents/com~apple~CloudDocs/Politecnico Torino/Anno 2024-2025/Primo Semestre/Numerical Optimization/Projects_Code/Numerical
                startedAt: "2025-08-24T08:49:03.429377Z"
                writerId: y6o1chsyvwf63dgdsgt5jzljv5rz5eqf
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 53
            "2":
                - 53
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.13.2
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
function:
    value: extended_rosenbrock
method:
    value: truncated
"n":
    value: 10000
