_wandb:
    value:
        cli_version: 0.21.1
        e:
            lgwu35ylnk5fqksb4wbjt6weu3wzqtlj:
                codePath: Test.py
                codePathLocal: Test.py
                email: salvatore.nocita25@gmail.com
                executable: C:\Users\salvo\AppData\Local\Programs\Python\Python312\python.exe
                git:
                    commit: 8bd3d1e8d6ab91fa069f3454cb749ab03049570f
                    remote: https://github.com/LucianoScarpino/Newton_Methods_Optimization.git
                host: LAPTOP-ALB2CGFI
                os: Windows-11-10.0.26100-SP0
                program: c:\Users\salvo\OneDrive\Desktop\model\Newton_Methods_Optimization\Test.py
                python: CPython 3.12.7
                root: C:\Users\salvo\OneDrive\Desktop\model\Newton_Methods_Optimization
                startedAt: "2025-08-19T12:21:23.387090Z"
                writerId: lgwu35ylnk5fqksb4wbjt6weu3wzqtlj
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 53
            "2":
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.7
            "5": 0.21.1
            "8":
                - 3
            "12": 0.21.1
            "13": windows-amd64
function:
    value: rosenbrock
method:
    value: truncated
"n":
    value: 2
